import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <ul className="flex justify-center gap-8 py-4">
            <li>Home</li>
            <li>about</li>
            <li>contact</li>
            <li>details</li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
